// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	openai "go-zero-chatgpt/openai/internal/handler/openai"
	"go-zero-chatgpt/openai/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/insert",
				Handler: openai.InsertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: openai.ChatHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/openai/v1"),
	)
}
