// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	Mobile string `json:"mobile"`
}

type UserInfoResp struct {
	Id         int64  `jsopn:"id"`
	Mobile     string `json:"mobile"`
	UserName   string `json:"username"`
	CreateTime string `json:"create_time"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
